### ISSUE TITLE
Consultation

### ISSUE THREAD

**Issue by damianlluch** [Rokt33r/aws-eb-typescript-app#5]
Hello, I came to this repository as I am dealing with the same issue. I have an application with Express, which I compile and upload the .zip code to Elastic BeanStalk, and I wanted to improve the process...
First I want to move the project to Typescript (I haven't managed to do it yet).

I have this configuration in tsconfig.json

```
{
  "compilerOptions": {
    "target": "es2016",
    "module": "commonjs",
    "esModuleInterop": true,
    "outDir": "./dist",
    "forceConsistentCasingInFileNames": true,
    "allowJs": true,
    "strict": true,
    "resolveJsonModule": true,
    "skipLibCheck": true
  },
  "include": ["api/**/*", "db.js", "app.js", "seeds/**/*"],
  "exclude": [ "node_modules"]
}
```

I've seen somewhere, that it creates a file 

```
buildspec.yml
```

I created it, and put this in it:

```
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16.17
    commands:
      - echo "Setting up the environment..."
  pre_build:
    commands:
      - echo "Installing source NPM dependencies..."
      - npm ci
  build:
    commands:
      - echo "Build started on `date`"
      - npm run tsc
  post_build:
    commands:
      - echo "Build completed on `date`"
artifacts:
  files:
    - dist/**/*
    - package.json
    - package-lock.json
cache:
  paths:
    - 'node_modules/**/*'
```

The zip file I'm uploading, I compress it like this

```
"compress": "zip -r komunicare.zip buildspec.yml api config app.js db.js package.js package.json package-lock.json -x \"node_modules/*" \"idea/*" \"test/*" \"*.ts"",
```

The problem I have is that it keeps running my project with Javascript, without compiling. In fact, I have changed the typescript compile command forcing the error, and I can't get Elastic BeanStalk to follow the steps I indicate in my buildspec.yml file.

Any suggestions?

thanks
